# Generated by Django 5.0.6 on 2024-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_cars_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
