# Generated by Django 5.0.6 on 2024-06-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
